### ISSUE TITLE
[sql-server-management-studio] Support Pre-Downloaded File

### ISSUE THREAD

**Issue by BlythMeister** [flcdrg/au-packages#100]
In order to save on bandwidth during a large rollout, i would like to pass a parameter of a pre-downloaded version of the installer

**Comment by flcdrg** [comment]
Hi @BlythMeister, can you clarify which package you're referring to here? I maintain quite a few!

**Comment by BlythMeister** [comment]
SQL server management studio.
The download is around 600mb, so downloading over and over has speed of rollout and bandwidth concerns

**Comment by flcdrg** [comment]
Might be worth having a look at https://stackoverflow.com/questions/18528919/how-do-i-install-chocolatey-packages-offline for some other ideas.

Essentially if you can copy the file into the temp directory (aka cacheLocation) then the downloader should notice it's already there and use it (if the checksums match). The trick is getting the path correct.

**Comment by BlythMeister** [comment]
I was thinking along the lines of the SQL server choco package which needs a ISO of SQL server.

You can provide this as a Param, but if Param not present, it does the download.

Not sure how easy that is to setup though!  I've only just started making my own packages.

**Comment by flcdrg** [comment]
yeah, it works for that package because as you say that mounts an ISO file, so there's a few more steps in the package script, compared to the SSMS one which is quite simple - just the one call that downloads and installs altogether.

**Comment by flcdrg** [comment]
Thanks, your PR is merged (plus some extra changes from me). Because this package already uses 4 part versioning, I can't really push a new version now. Instead we'll have to wait for Microsoft to release the next update of SSMS. That seems to be every few weeks so not too long to wait.
