### ISSUE TITLE
[PDFXChangeEditor] package parameters might be broken

### ISSUE THREAD

**Issue by flcdrg** [flcdrg/au-packages#102]
As per comment by Simon

**Comment by frznvm0** [comment]
You attempt to extract parameters from [an empty hash](https://github.com/flcdrg/au-packages/blob/master/PDFXchangeEditor/tools/chocolateyInstall.ps1#L57-L59).
Should be an easy fix

**Comment by flcdrg** [comment]
Oh.. yes, thanks. Looks like I didn't introduce `Get-PackageParameters` correctly.
