### ISSUE TITLE
[pdfxchangeeditor] checksum invalid

### ISSUE THREAD

**Issue by hobbes** [flcdrg/au-packages#114]
Hello, 

here is what I get when I try to install:

C:\WINDOWS\system32>cinst -y pdfxchangeeditor
Chocolatey v0.10.15
Installing the following packages:
pdfxchangeeditor
By installing you accept licenses for the packages.
Progress: Downloading PDFXchangeEditor 9.1.356.0... 100%

PDFXchangeEditor v9.1.356.0 [Approved]
pdfxchangeeditor package files install completed. Performing other installation steps.
WARNING: The download available at https://downloads.pdf-xchange.com/EditorV9.x86.msi has changed from what this package was expecting. Falling back to FTP for version-specific URL
WARNING: The download available at https://downloads.pdf-xchange.com/EditorV9.x64.msi has changed from what this package was expecting. Falling back to FTP for version-specific URL
Downloading PDFXchangeEditor 64 bit
  from 'http://www.docu-track.co.uk/builds/9.1.356.0/EditorV9.x64.msi'
WARNING: C:\Users\lybradmin\AppData\Local\Temp\chocolatey\PDFXchangeEditor\9.1.356.0\EditorV9.x64.msi is of content type text/html; charset=UTF-8

Download of EditorV9.x64.msi (-1 B) completed.
Error - hashes do not match. Actual value was 'BF268D562A7E80C0421DD362AF831F627F4EFBFF147F1CD054AD63C9E229B89B'.
ERROR: Checksum for 'C:\Users\lybradmin\AppData\Local\Temp\chocolatey\PDFXchangeEditor\9.1.356.0\EditorV9.x64.msi' did not meet '4D9936656FFA9826B4B1B2279DF7D722D10DD77DE10D8C89D8BDA329C4529EC0' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of pdfxchangeeditor was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\PDFXchangeEditor\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - pdfxchangeeditor (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\PDFXchangeEditor\tools\chocolateyInstall.ps1'.
 See log for details.

Thanks

**Comment by flcdrg** [comment]
Thanks, this should be fixed now.
