### ISSUE TITLE
Download URL for sql-server-2019-cumulative-update 15.0.4138.2 returns 404

### ISSUE THREAD

**Issue by mcx808** [flcdrg/au-packages#115]
The current download URL is 404 (https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB5003249-x64.exe)

Looks like CU12 was released just a few days ago so the chocolatey package needs an update.

**Comment by flcdrg** [comment]
Thanks for the notification. This package auto-updates though there was a small hiccup with the update script. It should be working now.

**Comment by mcx808** [comment]
I just checked again with sql-server-2019-cumulative-update.15.0.4153.1, same issue unfortunately.

Cumulative Update Package 12 for SQL Server 2019 - KB5004524:
https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB5004524-x64.exe

Package URL is:
https://download.microsoft.com/download/C/4/F/C4F908C9-98ED-4E5F-88D5-7D6A5004AEBD/SQLServer2017-KB4577467-x64.exe
