### ISSUE TITLE
[sql-server-2019-cumulative-update] Download URL for 15.0.4152.1 returns 404

### ISSUE THREAD

**Issue by mcx808** [flcdrg/au-packages#116]
I just checked again with sql-server-2019-cumulative-update.15.0.4153.1, same issue as https://github.com/flcdrg/au-packages/issues/115 unfortunately.

Cumulative Update Package 12 for SQL Server 2019 - KB5004524:
https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB5004524-x64.exe

Package URL is:
https://download.microsoft.com/download/C/4/F/C4F908C9-98ED-4E5F-88D5-7D6A5004AEBD/SQLServer2017-KB4577467-x64.exe

**Comment by flcdrg** [comment]
Can you double check this?

https://community.chocolatey.org/packages/sql-server-2019-cumulative-update/15.0.4153.1 (aka CU 12)

Contains this
```powershell
$url        = 'https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB5004524-x64.exe'
$checksum   = 'c6d7bd9ebc82a68ea2d70638312120cea66db7bd633e82943d94035ec73a9934'
$softwareName = 'Hotfix 4153 for SQL Server 2019*(KB5004524)*'
```

The download site https://www.microsoft.com/en-us/download/details.aspx?id=100809 currently lists:

![image](https://user-images.githubusercontent.com/384747/130706540-d266ad68-98da-4211-aaa2-ff2b07e0c80d.png)

and links to https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB5004524-x64.exe which looks like the same URL (and the download is working for me)

**Comment by flcdrg** [comment]
Oh.. just noticed - your second link is for SQL 2017!

**Comment by mcx808** [comment]
Is there any way you can increment or append the package version number so I can check? 
I re-publish the public nuget packages to an internal nuget repo, but this means I cannot republish any package with the same version number as nuget feeds are idempotent.

**Comment by flcdrg** [comment]
https://community.chocolatey.org/packages/sql-server-2019-cumulative-update/15.0.4153.1 is the latest for 2019

Chocolatey has the same rules - each package version is idempotent and can't be replaced once it is public.

Your second link is referencing SQL 2017, but the package you've mentioned is for 2019. Are you sure you haven't got them confused?

**Comment by flcdrg** [comment]
Closing this for now
