### ISSUE TITLE
sql-server-management-studio: incorrect package version 

### ISSUE THREAD

**Issue by amlugnaur** [flcdrg/au-packages#134]
Hi,

The latest release mention a version 18 but it's still referenced as version 15 into chocolatey community.

Perhaps the prolem is located into the .nuspec file as it's mentioned version 15.0.18424.0

`<version>15.0.18424.0</version>
    <packageSourceUrl>https://github.com/flcdrg/au-packages/tree/master/sql-server-management-studio</packageSourceUrl>
    <owners>flcdrg</owners>
    <title>**SQL Server Management Studio 18.12.1</title>
    <authors>Microsoft</authors>`

**Comment by flcdrg** [comment]
This is already documented in the package description

> This package is versioned using the published build number. The corresponding 'release number' is included in the package title
