### ISSUE TITLE
[DellCommandUpdate] 4.6 is the last version 

### ISSUE THREAD

**Issue by flcdrg** [flcdrg/au-packages#138]
As per https://www.dell.com/support/kbdoc/en-au/000177325/dell-command-update

> NOTE: Dell Command | Update Classic interface is not supported from version 4.7 onwards and the older Dell Command | Update Classic clients are upgraded to Dell Command | Update version 4.7 UWP 

Probably need to mark this package as 'done' with a note for people to switch to https://community.chocolatey.org/packages/DellCommandUpdate-uwp if they're on Windows 10+

**Comment by flcdrg** [comment]
Did you try `choco uninstall dellcommandupdate` ?

**Comment by IMWS-User** [comment]
No, I’ll try.

Nevertheless: The dellcommandupdate-uwp package installs without GUI. I’ve tried with choco install and double-clicking in windows explorer.
Is this missing GUI intended when installing the uwp-version?

Von: David Gardiner ***@***.***>
Gesendet: Samstag, 19. November 2022 07:38
An: flcdrg/au-packages ***@***.***>
Cc: Lohner, Martin ***@***.***>; Comment ***@***.***>
Betreff: Re: [flcdrg/au-packages] [DellCommandUpdate] 4.6 is the last version (Issue #138)


Did you try choco uninstall dellcommandupdate ?

**Comment by flcdrg** [comment]
I use dellcommandupdate-uwp myself. Definitely has a GUI (looks basically the same as the non-UWP one as far as I can tell)
![image](https://user-images.githubusercontent.com/384747/203176426-a17387e1-f12e-4c3c-8869-2ca339c4a8ed.png)

Don't think you can have both versions installed at the same time, so make sure any existing dellcommandupdate(s) are uninstalled first.

**Comment by IMWS-User** [comment]
Hi David,

on one WIN 11 computer I did „choco uninstall dellcommandupdate” and „choco uninstall dellcommandupdate-uwp”
Both commands resulted in “packages not installed”

In “Settings -> installed apps” there was a “Dell Command | update “ shown as installed.

Only after deinstalling that app manually, I was able to install “choco install dellcommandupdate-uwp” successfully.

This time with GUI.

On another computer:

choco uninstall dellcommandupdate

choco install dellcommandupdate-uwp

Resulted in a working dcu-4.6-uwp.

Nevertheless, during installation a terminal popped up, asking for a “C” to continue.
(See attachachment)
After some time (appr. 15 second) the window closed without an entered “C”.

For unattended installation, the windows should not pop up.



Von: David Gardiner ***@***.***>
Gesendet: Dienstag, 22. November 2022 00:13
An: flcdrg/au-packages ***@***.***>
Cc: Lohner, Martin ***@***.***>; Comment ***@***.***>
Betreff: Re: [flcdrg/au-packages] [DellCommandUpdate] 4.6 is the last version (Issue #138)


I use dellcommandupdate-uwp myself. Definitely has a GUI (looks basically the same as the non-UWP one as far as I can tell)
[image]<https://user-images.githubusercontent.com/384747/203176426-a17387e1-f12e-4c3c-8869-2ca339c4a8ed.png>

Don't think you can have both versions installed at the same time, so make sure any existing dellcommandupdate(s) are uninstalled first.

**Comment by flcdrg** [comment]
Having existing versions of dcu installed is not something the package can handle.

The attachment didn't come through. Can you post it via github.com rather than email - I'd be curious to see that.

**Comment by IMWS-User** [comment]
Here it is:

![IMG_5215](https://user-images.githubusercontent.com/113602617/203310172-8c1045cc-7263-49c0-8aef-2d0905b9124b.jpg)

**Comment by flcdrg** [comment]
My high school German is too rusty, but Google Translate saved the day!

That is a strange one. It's a CMD process (not PowerShell), so I'm pretty sure it isn't Chocolatey doing that. It might be something launched by the DCU installer itself, in which case it might be something to take up (or search for) with Dell.

**Comment by IMWS-User** [comment]
I have to apology for posting this error.
It is not generated by chocolatey.
It was a post-install script triggering dcu on command line.
Sorry.

Von: David Gardiner ***@***.***>
Gesendet: Mittwoch, 23. November 2022 02:56
An: flcdrg/au-packages ***@***.***>
Cc: Lohner, Martin ***@***.***>; Comment ***@***.***>
Betreff: Re: [flcdrg/au-packages] [DellCommandUpdate] 4.6 is the last version (Issue #138)


My high school German is too rusty, but Google Translate saved the day!

That is a strange one. It's a CMD process (not PowerShell), so I'm pretty sure it isn't Chocolatey doing that. It might be something launched by the DCU installer itself, in which case it might be something to take up (or search for) with Dell.

**Comment by flcdrg** [comment]
ah.. good to know the cause.
