### ISSUE TITLE
Please add a way to install .NET JetBrains tools like DotPeek for all users

### ISSUE THREAD

**Issue by Destroy666x** [flcdrg/au-packages#143]
Either by default or with a parameter like `/AllUsers`. The installer switch that is needed is `/PerMachine` from what I see: https://www.jetbrains.com/help/resharper/Installation_Guide.html#install-for-all-users

**Comment by flcdrg** [comment]
I've made changes to support this in the same way that we already have for the dotUltimate package. It will be included in in the next package versions that are published.

**Comment by Destroy666x** [comment]
Thank you!
