### ISSUE TITLE
[dellcommandupdate-uwp] version 4.7.1

### ISSUE THREAD

**Issue by umol-unibas** [flcdrg/au-packages#145]
Hi David,

could you please update your _**update.ps1**_ for Dell Command Update (UWP)? Version 4.7.1 is out. I found this cab where the correct links are included. Maybe you can have a look at it:

[DELL APP Catalog PC](https://downloads.dell.com/catalog/DellAppCatalogPC.cab)

Thank you!

BTW: what a mess with the upgrade to UWP and the need for opening a new package to it. Do you know what the between UWP and non-UWP is?

**Comment by flcdrg** [comment]
Thanks, I'll take a look. For the last week, the update.ps1 has been finding 4.7 in one of the .cab files but the URL appears to be invalid so it wasn't updating the package. I'd also noticed my own copy of DCU UWP wasn't offering me an update from 4.6.

Yes, Dell have made this messy. I'm not actually sure there's much difference at all between the two - last time I looked they seemed pretty much identical!

**Comment by umol-unibas** [comment]
Thanks for your help and updating DCU! I close the issue. Have a nice day!
