### ISSUE TITLE
"New Teams" vs "Teams Classic"

### ISSUE THREAD

**Issue by teknowledgist** [flcdrg/au-packages#156]
Hi.  Just an FYI in case you aren't aware that the microsoft-teams package is installing "Microsoft Teams classic" as MS has renamed it, and there is [a replacement product coming](https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin).

Teams has always been a PITA for sysadmins, so MS had to go make it worse.  :-(  In case you will be taking on the job of building/maintaining a package for "New Teams", there is [information on install here](https://learn.microsoft.com/en-us/microsoftteams/new-teams-bulk-install-client#step-1-upgrade-the-new-teams-application). 

Thanks for the good work you do for the community and good luck!

**Comment by flcdrg** [comment]
Thanks for the heads up. I had started to look at how the new version is distributed. Will be an interesting one!

**Comment by flcdrg** [comment]
I've updated the package names for the 'classic' packages and I've created https://community.chocolatey.org/packages/microsoft-teams-new-bootstrapper to run the current bootstrapper.

Sounds like in the near future there will be a self-contained bootstrapper which sounds closer to the existing packages. I may add another package to cater for that, depending on what it looks like.
