### ISSUE TITLE
[lenovo-thinkvantage-system-update] More reliable version detection for Lenovo-System-Update

### ISSUE THREAD

**Issue by SebastianK90** [flcdrg/au-packages#158]
Hello,

I have a suggestion for improving the update.ps1
Perhaps you can better recognize the version in the long term with the following changes?

    $response = Invoke-WebRequest -Uri "https://support.lenovo.com/us/en/downloads/ds012808-lenovo-system-update-for-windows-10-7-32-bit-64-bit-desktop-notebook-workstation" -UseBasicParsing
    $pattern = '(?<="Name":"Lenovo\ System\ Update")[\S\s]*,"Version":"(?<Version>[\d\.]+)'
    $version = [regex]::Match($response.Content, $pattern).groups['Version'].value

Thanks!

**Comment by flcdrg** [comment]
I might add that as a fallback. I'd prefer to stick with the "official" data feed, but it's weird even Lenovo seem to have stopped using it (in that the feed hasn't been updated to point to the newer version, and using Fiddler I can see even the new version is still querying the same feed)

**Comment by flcdrg** [comment]
Thanks for your help!
