### ISSUE TITLE
[ubiquiti-unifi-controller] Update to 8.0.7

### ISSUE THREAD

**Issue by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [flcdrg/au-packages#160]
See https://www.ui.com/download/releases/network-server

**Comment by flcdrg** [comment]
Yeah.. Looks like they changed their web page so I can't rely on the previous data feed for updates. Will need to dig in to see if there's another data feed that can be used instead.

**Comment by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [comment]
Try https://download.svc.ui.com/v1/software-downloads. It seems to have a similar structure. You an filter using `.platform -eq "windows"` and `product_lines` contains "unifi", the sort by version and use the `file_path`. I'm not that good with powershell, but in jq it looks like

```jq
.downloads | map(select(.platform == "windows") | select(.product_lines | any(. == "unifi")) | {name,version,file_path}) | sort_by(.version) | last
```
