### ISSUE TITLE
microsoft-teams-new-bootstrapper hash mismatch

### ISSUE THREAD

**Issue by shuuryou** [flcdrg/au-packages#162]
Installing `microsoft-teams-new-bootstrapper` package is currently failing because of a Hash mismatch:

```
Error - hashes do not match. Actual value was '596B858EFA3A353D91B95525515CB09F42263AF99C6233BC49399D6D0E76EFB5'.
ERROR: Checksum for 'C:\ProgramData\chocolatey\lib\microsoft-teams-new-bootstrapper\tools\teamsbootstrapper.exe' did not meet '9BA82898539EEDF786346C17041A072C7002541504BAF4B1612F2D097EB9CC81' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
```

It might be tough to keep up with the hyperactive devs at Microsoft unless you do an automated hourly check if the installer's hash has changed or something to that effect. I'm working around it using `--ignore-checksums` for now, but wanted to give you a heads-up.

**Comment by flcdrg** [comment]
Yeah, this is a challenge with software that is updated frequently but doesn't change the download URL or allows redistribution.

I have an update script in place now and it has picked up a new version. Until the package is 'trusted', it needs to wait for a moderator to review it, which can take a while sometimes.
