### ISSUE TITLE
Lenovo System Update Uninstall Failing

### ISSUE THREAD

**Issue by ScottMonolith** [flcdrg/au-packages#165]
The uninstall throws an error:

`Uninstalling lenovo-thinkvantage-system-update...
WARNING: MSI could not be found - it is possibly corrupt or not an MSI at all. If it was downloaded and the MSI is less than 30K, try opening it in an editor like Notepad++ as it is likely HTML. This is most likely an issue with the 'lenovo-thinkvantage-system-update' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly.
ERROR: Running ["C:\WINDOWS\System32\msiexec.exe" /x TVSU_is1 /qn /norestart ] was not successful. Exit code was '1619'. Exit code indicates the following: MSI could not be found - it is possibly corrupt or not an MSI at all. If it was downloaded and the MSI is less than 30K, try opening it in an editor like Notepad++ as it is likely HTML. This is most likely an issue with the 'lenovo-thinkvantage-system-update' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly..
lenovo-thinkvantage-system-update uninstall not successful.
Error while running 'C:\ProgramData\chocolatey\lib\lenovo-thinkvantage-system-update\tools\chocolateyuninstall.ps1'.
See log for details.`

See here - http://disq.us/p/2x5f5oi

I have created a PR, this method seems to work successfully from what I can tell.

#164

**Comment by flcdrg** [comment]
Thanks. Unfortunately because Lenovo already use 4-part version numbers I can't create a 'date-fix' version, but the next release that Lenovo publish will incorporate your fixes

**Comment by ScottMonolith** [comment]
Ah, alright.  Thanks for accepting the PR so quickly!  In the meantime I'll just direct folks to do a manual uninstall if needed.
