### ISSUE TITLE
[dellcommandupdate] Installing version 5.2.0 fails

### ISSUE THREAD

**Issue by olifre** [flcdrg/au-packages#170]
Latest approved version can not be downloaded by Chocolatey:
```
dellcommandupdate v5.2.0 [Approved]
 dellcommandupdate package files upgrade completed. 
Performing other installation steps. Attempt to get headers for https://dl.dell.com/FOLDER11201514M/1/Dell-Command-Update-Application_4R78G_WIN_5.2.0_A00.EXE failed. 
The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://dl.dell.com/FOLDER11201514M/1/Dell-Command-Update-Application_4R78G_WIN_5.2.0_A00.EXE'. 
Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
```
Downloading via `curl` fails, too, but downloading via browser appears to work, so probably Dell is performing a user agent check or similar.

**Comment by flcdrg** [comment]
Thanks for the report. I've delisted that version while I investigate.

**Comment by flcdrg** [comment]
I've just pushed 5.2.0.20240212 which sets the user-agent string.

Note that there is still an error reported due to https://github.com/chocolatey/choco/issues/3191, but this doesn't stop the download and install should be able to proceed.

**Comment by olifre** [comment]
Many thanks for the quick action, both in removing the new version and fixing things by adjusting to Dell servers being selective, sending the user agent did the trick — and of course thanks for maintaining this (and other packages)!
