### ISSUE TITLE
[microsoft-teams-new-bootstrapper] Add support for systemwide install of the Outlook meeting Add-in

### ISSUE THREAD

**Issue by michael-franck** [flcdrg/au-packages#175]
Allow for systemwide installation of the Teams Outlook meeting add-in.
This currently is not enabled and as such it doens't work in a non-persistent environment.

https://learn.microsoft.com/en-us/microsoftteams/new-teams-vdi-requirements-deploy#teams-meeting-add-in

**Comment by flcdrg** [comment]
Note that we'll have to wait for the next version update from Microsoft to trigger a new package being published to Chocolatey that includes this functionality
