### ISSUE TITLE
sql-server-management-studio KB2919355 dependency causes install failure on Server 2016.

### ISSUE THREAD

**Issue by affieuk** [flcdrg/au-packages#18]
The dependency for KB2919355 cause the install to fail on server 2016.

https://github.com/flcdrg/au-packages/blob/6b4d8fbe7929ee6bf2dba9defdf635fb64c62fb7/sql-server-management-studio/sql-server-management-studio.nuspec#L141

**Comment by flcdrg** [comment]
Hmm.. do you have the chocolatey log for this?

We may need to push this back to the maintainer of the KB2919355 Chocolatey package if that update should be skipped on 2016.

That package lives in https://github.com/riezebosch/BoxstarterPackages
/cc  @riezebosch

**Comment by riezebosch** [comment]
I suppose it already [does](https://github.com/riezebosch/BoxstarterPackages/blob/master/KB2919355/Tools/ChocolateyInstall.ps1#L8)?

**Comment by flcdrg** [comment]
Just fired up a new Windows Server 2016 VM, and confirmed that the SSMS package does install correctly without error.

@affieuk Maybe you had a pending reboot? Reviewing your chocolatey.log file should give you more info about what the root cause was for this.

**Comment by affieuk** [comment]
Strangely it was a new vm that I got this error on, but can't reproduce anymore. So chalk this down to user error.
