### ISSUE TITLE
[ubiquiti-unifi-controller] Installation issues, AutoHotkey error: Error: Function calls require a space or "(".

### ISSUE THREAD

**Issue by asheroto** [flcdrg/au-packages#188]
When installing on Windows 11 Pro, this error appears:

```
Error: Function calls require a space or "(". Use comma only between parameters.
```

![Screenshot 2024-11-05 155234](https://github.com/user-attachments/assets/a6e7a462-14bb-42e6-a248-ad259c24be68)

**Comment by asheroto** [comment]
I believe this may be because AutoHotkey portable was upgraded to version 2 of AutoHotkey. Similar to #147.

**Comment by asheroto** [comment]
![image](https://github.com/user-attachments/assets/3ffdd086-951f-4045-a817-32627bb6ebd2)

still an issue

**Comment by flcdrg** [comment]
Thanks for the reminder. I might get a chance to look at this over the Christmas break.

**Comment by asheroto** [comment]
Hey there, Merry Christmas! It actually seems to work without it. I can click Exit App and it seems to function, so. might be a quick fix.

**Comment by flcdrg** [comment]
I think this update should resolve the v2 compatibility issues. I did some testing and I think it works ok for install/uninstall and upgrading. Should be picked up by the next package version(s)

**Comment by asheroto** [comment]
Nice! Thanks for your time!
