### ISSUE TITLE
[azure-pipelines-agent] Error when installing with --package-params via ansible

### ISSUE THREAD

**Issue by tdietrich513** [flcdrg/au-packages#44]
I'm attempting to install the azure-pipelines-agent from a win_chocolately module within ansible. This is the command that it ends up attempting to execute: (sensitive info has been replaced with ***)
`C:\ProgramData\chocolatey\bin\choco.exe install azure-pipelines-agent --fail-on-unfound --yes --no-progress --limit-output --package-parameters "/Url:https://*****.visualstudio.com /Token:****** /Pool:default /DeploymentGroup /ProjectName:*** /DeploymentGroupName:*** /DeploymentGroupTags:***" --timeout 2700`

This install call is resulting in the following error message:

```
ERROR: Method invocation failed because [System.Object[]] does not contain a method named 'op_Addition'.
The install of azure-pipelines-agent was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\azure-pipelines-agent\tools\chocolateyinstall.ps1'.
 See log for details.
```

I think the problem is on this line: 
            `$configOpts =+ @("--deploymentGroupTags", $pp['DeploymentGroupTags'])`

A pull request has been submitted to correct this issue. #43

**Comment by tdietrich513** [comment]
could we get a minor release pushed with this fix?

**Comment by flcdrg** [comment]
Yes. I pushed an updated package. It's awaiting moderation but you can use it explicitly if you specify the version number

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
