### ISSUE TITLE
[azure-pipelines-agent] Deployment Group Tags do not get registered

### ISSUE THREAD

**Issue by tdietrich513** [flcdrg/au-packages#47]
Specifying Deployment Group Tags does not result in the deployment agent registering with azure devops with the provided tags. A pull request (#46 ) has been submitted with a fix- turns out you have to provide a flag as well as the list of deployment group tags for it to handle it properly.

**Comment by tdietrich513** [comment]
Is there a release pending for this fix?

**Comment by flcdrg** [comment]
New packages are published automatically when Microsoft release a new version on github.

If that doesn't happen soon, I might be able to do an interim update

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
