### ISSUE TITLE
[azure-pipelines-agent]Add support for --work parameter

### ISSUE THREAD

**Issue by flcdrg** [flcdrg/au-packages#50]
We should support the --work parameter to specify the agent work directory

**Comment by bergmeister** [comment]
+1 Using the D drive as a working directory on Azure VMs (where the D drive is a physical drive) yields a big performance improvement

**Comment by flcdrg** [comment]
This should appear in the next version of the package

**Comment by bergmeister** [comment]
Awesome, thank you very much
