### ISSUE TITLE
Take over my SqlSearch package?

### ISSUE THREAD

**Issue by sumo300** [flcdrg/au-packages#56]
Since you already have an auto-updating package for the Red Gate SQL Toolbelt, are you interested in adding SqlSearch to your list and taking ownership of it?  I'm the current owner of the package on chocolatey.org and my package source is here on GitHub.

https://github.com/sumo300/chocolatey-sqlsearch

**Comment by flcdrg** [comment]
Hi Michael,

sure, I'd be happy to do that. If you'd like to add me as a package maintainer in Chocolatey, then I'll copy over the package source and get an update.ps1 script going for it.

David

**Comment by sumo300** [comment]
@flcdrg All taken care of.
