### ISSUE TITLE
[Feature Request] Add dotMemory standalone test runner

### ISSUE THREAD

**Issue by lavahot** [flcdrg/au-packages#61]
There's a standalone test runner available for dotMemory. It would be pretty great to have a chocolatey package for it.

**Comment by flcdrg** [comment]
Are you referring to the dotMemory command line tools, or something else?

**Comment by lavahot** [comment]
Specifically this thing here: https://www.jetbrains.com/dotmemory/unit/

**Comment by flcdrg** [comment]
Pushed new package to https://chocolatey.org/packages/dotmemory-unit

**Comment by lavahot** [comment]
Dude, you rule. Thank you!
