### ISSUE TITLE
[azure-pipelines-agent] Add support for SSL parameters

### ISSUE THREAD

**Issue by gregnorz** [flcdrg/au-packages#62]
There are several parameters around SSL and self-signed certificates which could be easily passed to the underlying agent .exe:

`--gituseschannel`
`--sslcacert`
`--sslclientcert`

...just to name a few.

Documentation from MS here: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/certificate?view=azure-devops-2019&viewFallbackFrom=azure-devops

**Comment by gregnorz** [comment]
I might have some time in the coming days to take a look at this and fork the repo.

**Comment by flcdrg** [comment]
That would be great. PRs are welcome

**Comment by flcdrg** [comment]
Some more here too - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/certificate?view=azure-devops-2019

**Comment by gregnorz** [comment]
Gah, I let this fall off of my radar as my client has moved to the cloud-based Azure, no longer needing to configure agents to hit a local, self-signed Azure DevOps Server.

To get this working, I think all we (I) need to do is add in these params which are parsed and passed automatically to the choco package. Correct? From what I remember digging in the source, there wasn't much special handling needed, unless we wanted to do some checking to make sure the combination of params matched what the agent installer wanted.

**Comment by blakeduffey** [comment]
Hello all.  Any idea when this might support --gituseschannel ?
Thanks

**Comment by blakeduffey** [comment]
Anyone?

**Comment by flcdrg** [comment]
@blakeduffey PRs are welcome!
