### ISSUE TITLE
SSMS fails to launch - [Splash screen only appears]

### ISSUE THREAD

**Issue by OraDotNetDev** [flcdrg/au-packages#64]
When attempting to launch SQL Server Management Studio, only the splash screen appears.

This is a [known issue](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#bug-fixes-in-181) with version 18.0, v18.1 released yesterday, 11-June-2019 fixes this.  

[workaround](https://feedback.azure.com/forums/908035-sql-server/suggestions/37502512-ssms2018-installed-but-will-not-run) see "**Show previous admin responses**"

**Comment by flcdrg** [comment]
18.1 is now published

**Comment by OraDotNetDev** [comment]
Thanks very much for you help on this Eric :smiley:  

Now successfully using the updated package.

**Comment by OraDotNetDev** [comment]
Thanks very much for you help on this David :smiley:  

Now successfully using the updated package.
