### ISSUE TITLE
[microsoft-teams.install] 

### ISSUE THREAD

**Issue by flcdrg** [flcdrg/au-packages#66]
Warning reported by loeffel:

```
WARNING: This MSI requires uninstall prior to installing a different version. Please ask the package maintainer(s) to add a check in the chocolateyInstall.ps1 script and uninstall if the software is installed. This is most likely an issue with the 'microsoft-teams.install' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly.
```

**Comment by Anitalex** [comment]
This does not place an icon on the desktop and is not searchable on the start menu.  You have to go to C:\Windows\SysWOW64\config\systemprofile\AppData\Local\Microsoft\Teams\Programs\Microsoft Corporation\ to get the shortcut and then place it on the public desktop

**Comment by jessetn** [comment]
I had this as well, and wasn't showing up in Control Panel -> Programs and Features.  Need to also make sure it's uninstalled from the Settings app -> Apps & Features, and uninstall "Teams Machine-Wide Installer".  Not sure of an automated way to do this
https://support.office.com/en-us/article/uninstall-microsoft-teams-3b159754-3c26-4952-abe7-57d27f5f4c81

**Comment by flcdrg** [comment]
I've changed the package so that for future versions, it includes a chocolateybeforemodify.ps1, so that before an upgrade the current version will be uninstalled. That should make the upgrade for installing the next new version happier.
