### ISSUE TITLE
Could you re-publish Redgate SQL Search?

### ISSUE THREAD

**Issue by rhowe** [flcdrg/au-packages#72]
It looks like Redgate have done some rearranging of the SQL Search binary on their site. Whilst the file hasn't changed checksum, it has changed timestamps:

```
chocolatey.log:
2019-10-28 12:02:41,042 19076 [INFO ] - VERBOSE: Package LastModified: 09/03/2019 12:47:27 +00:00
2019-10-28 12:02:41,045 19076 [INFO ] - VERBOSE: HTTP Last Modified  : 09/27/2019 13:20:55 +00:00
```

This timestamp of the 27th September also correlates with this URL: https://download.red-gate.com/installers/SQL_Search/2019-09-27/SQL_Search.exe

Unfortunately because I'm behind a firewall which restricts FTP access, the fallback to FTP download doesn't work for me.

Is it possible to republish SQL Search to chocolatey in order to pick up the revised timestamp and remove the FTP fallback (removed in commit 933851a45a4b6563e418ef715ff568f23c8be616)?

Thanks

**Comment by flcdrg** [comment]
Hmm.. I thought we'd reworked all the Red Gate products so they didn't need FTP any more. But now that I look at https://github.com/flcdrg/au-packages/blob/master/SqlSearch/tools/chocolateyInstall.ps1 I can see that actually it's *only* using FTP!

That's definitely a bug. I'll try and have a look, unless @nicolasvan wants to jump in

**Comment by flcdrg** [comment]
I've switched SqlSearch to use the new yyyy.mm.dd versioning (which also should result in the new package just using https and not FTP anymore).

Hopefully the new package version will appear shortly

**Comment by rhowe** [comment]
Looks good to me!

```
>choco install sqlsearch
Chocolatey v0.10.11 Business
Running in background mode
Installing the following packages:
sqlsearch
By installing you accept licenses for the packages.

Progress: Downloading SqlSearch 2019.09.27... 100%
SqlSearch v2019.09.27
sqlsearch package files install completed. Performing other installation steps.
Using explicit proxy server '<blah>'.
Using explicit proxy server '<blah>'.
Downloading SqlSearch
  from 'https://download.red-gate.com/installers/SQL_Search/2019-09-27/SQL_Search.exe'
Using explicit proxy server '<blah>'.

Progress: 100% - Completed download of 'SQL_Search.exe' (11.33 MB).
Download of 'SQL_Search.exe' (11.33 MB) completed.
Virus checking skipped/turned off. Not verifying 'SQL_Search.exe'
Hashes match.
Installing SQL_Search.exe...
SQL_Search.exe has been installed.
 The install of sqlsearch was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```
