### ISSUE TITLE
[sql-server-management-studio] Check for new version is broken

### ISSUE THREAD

**Issue by 657870** [flcdrg/au-packages#75]
Microsofot has changed the markup within their docs. Your check don't work anymore. I don't know if you need the localization specific URL links but in case of not, you should change the URL in something like: https://aka.ms/ssmsfullsetup

https://github.com/flcdrg/au-packages/blob/58e67e3664dc72cc3324bb58c6d1bc02fda4f2e9/sql-server-management-studio/update.ps1#L84

**Comment by flcdrg** [comment]
Thanks for the info. I've updated update.ps1 so it should work correctly now.
