### ISSUE TITLE
[microsoft-teams.install] add noAutoStart and allusers install optilm

### ISSUE THREAD

**Issue by JudgeDreddKLC** [flcdrg/au-packages#92]
Options should be selectable individually, either noAutoStart or ALLUSERS or both. 

msiexec /i Teams_windows_x64.msi OPTIONS="noAutoStart=true" ALLUSERS=1

Please note this package installation needs to be elevated for these features to work 

From the MS documentation:
If you run the MSI manually, be sure to run it with elevated permissions. Even if you run it as an administrator, without running it with elevated permissions, the installer won't be able to configure the option to disable auto start.

**Comment by flcdrg** [comment]
@JudgeDreddKLC this feature has been added but you will need to wait for the next version of Teams to be published by Microsoft before a new package is created that uses the changes.

(Because Teams already uses a 4-part version, I can't manually push a new package version)
